### ISSUE TITLE
Could you share server side hash generation code 

### ISSUE THREAD

**Issue by pawarlalit29** [khushvindersharma/kpblogs#1]
Could you share server side hash generation code   

//TODO Below url is just for testing purpose, merchant needs to replace this with their server side hash generation url
                URL url = new URL("https://www.khreedle.com/getHashCode.php");

**Comment by khushvindersharma** [comment]
​you can copy from my post:

https://kpblogs.com/mobile-development/payumoney-payment-gateway-integration-with-android/

Thanks,
Khushvinder​

Thank You,
Khushvinder Pal,
9810093311
https://kpblogs.com/

**Comment by pawarlalit29** [comment]
thanks :+1:
